### PR TITLE
Mount

### PR DESCRIPTION
**Pull request by Carbonique**
Hi there,

I'm back at it again! This PR implements functionality to mount volumes to a mountpoint, without having to specify the slot. To do so, I have changed `Mount()` to `MountSlot()` and I have introduced the function `MountPath()`.

`MountPath()` makes life easier when managing many volumes, as the user no longer has to keep track of which slots are in use already. Instead, the user can just focus on mounting volumes to a path.

### CODE REVIEW

**Comment by mark-hartmann** [comment]
Thank you for your further contribution, I appreciate it. I found some minor issues (documentation comments) but already fixed them.

One question comes to my mind though, is there a specific reason why you created another container called `basic2.vc`, which is at least superficially no different from `basic.vc`? For the test `TestPathVolumeMountpointInUse` one of the already existing containers should also work, shouldn't it?

**Comment by Carbonique** [comment]
Good one! I think you are right: the existing containers should be enough for that test. Let me remove the new container today!

**Comment by Carbonique** [comment]
Removed the container! Thanks for noticing

**Comment by mark-hartmann** [comment]
Looks good, but `testmountpoint` is already tracked by git, so no need to mention it in the README.md

**Comment by Carbonique** [comment]
You're right, I changed the readme

**Pull request merged**
